### ISSUE TITLE
computed_field_FIELD_MACHINE_NAME_compute() is executed thrice

### ISSUE THREAD

**Issue by guidot** [backdrop-contrib/computed_field#6]
Settings:
 * OFF Recalculate the field value every time
 * OFF Store value in the database
 * OFF Index computed values in the database
 
When I save an edited node with a computed field I can see (by some dpm() calls) that the compute function is called three times:
The first time using the old values (from before the node was edited)
The second and third time using the new values.
 
 ```
 function computed_field_field_actual_value_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
  $entity_wrapper = entity_metadata_wrapper($entity_type, $entity);
  $use_default = $entity_wrapper->field_use_default->value();
  if ($use_default) {
    if (isset($entity_wrapper->field_myparent)) {
      dpm('Parent value');
      $parent_entity = $entity_wrapper->field_myparent->value();
      $parent_wrapper = entity_metadata_wrapper($entity_type, $parent_entity);
      $entity_field[0]['value'] = $parent_wrapper->field_question_text->value();
    } else {
      dpm('Nothing');
      $entity_field[0]['value'] = '';
    }
  } else {
    dpm('My value');
    $entity_field[0]['value'] = $entity_wrapper->field_question_text->value();
  }
}
 ```
 I'd prefer only a single calculation.

**Comment by robertgarrigos** [comment]
In this case, backdrop call a load function in the first place, when you save a node, which triggers a computed field function which do the computing. Then, a hook to update the node is called, which triggers another computed field function which does the computing. Finally, a load hook is called again before to show the node again, once saved.

If you set ON to Store value in the database, you will save the two load calls and will have a single running of the computing.

Because you are not saving the value in the database, computed field has to run the compute function on every load. Otherwise, you would see any value at all.
